/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Every third number in Fibonacci array is even.
Furthermore, with a little bit of playing, you can get to the formulas x = x + 2 * y, y = 2 *x + 3 * y for calculating the next even number.

*/

function sumOfEvenFibonacci(){
  var total = 0;
  var prev = 1;
  var even = 2; 
  var tPrev, tEven;

  while(even < 4000000){
    total += even;
    tPrev = prev + 2 * even;
    tEven = 2 * prev + 3 * even;
    prev = tPrev; 
    even = tEven;
  }
  return total;
}